package com.eko.nerdeneyenir.model;

// default package
// Generated 27.Tem.2014 21:21:56 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

/**
 * Food generated by hbm2java
 */

public class EkoUtil implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private String ekoKey;
	private String ekoValue;
	
	public EkoUtil(){
		
	}
	
	public String getEkoKey() {
		return ekoKey;
	}

	public void setEkoKey(String ekoKey) {
		this.ekoKey = ekoKey;
	}

	public String getEkoValue() {
		return ekoValue;
	}

	public void setEkoValue(String ekoValue) {
		this.ekoValue = ekoValue;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((ekoKey == null) ? 0 : ekoKey.hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object object) {
		if (!(object instanceof EkoUtil)) {
			return false;
		}
		EkoUtil other = (EkoUtil) object;
		if ((this.ekoKey == null && other.ekoKey != null)
				|| (this.ekoKey != null && !this.ekoKey.equals(other.ekoKey))) {
			return false;
		}
		return true;
	}

	@Override
	public String toString() {
		return "EkoUtil[" + this.ekoKey + " = " + this.ekoValue + "]";
	}

}
