package com.eko.nerdeneyenir.model;

// default package
// Generated 27.Tem.2014 21:21:56 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

import com.owlike.genson.annotation.JsonIgnore;

/**
 * Food generated by hbm2java
 */

public class FoodImage implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer foodImageId;
	private Food food;
	private String foodImage;
	private Date insertDate;

	public FoodImage() {
		this.setInsertDate(new Date());
	}

	public FoodImage(Integer foodImageId, Food food, String foodImage, Date insertDate) {
		super();
		this.foodImageId = foodImageId;
		this.food = food;
		this.foodImage = foodImage;
		this.insertDate = insertDate;
	}

	public Integer getFoodImageId() {
		return foodImageId;
	}

	public void setFoodImageId(Integer foodImageId) {
		this.foodImageId = foodImageId;
	}

	@JsonIgnore
	public Food getFood() {
		if(food == null){
			food = new Food();
		}
		return food;
	}

	public void setFood(Food food) {
		this.food = food;
	}

	public String getFoodImage() {
		return foodImage;
	}

	public void setFoodImage(String foodImage) {
		this.foodImage = foodImage;
	}

	public Date getInsertDate() {
		return insertDate;
	}

	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((foodImageId == null) ? 0 : foodImageId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object object) {
		if (!(object instanceof FoodImage)) {
			return false;
		}
		FoodImage other = (FoodImage) object;
		if ((this.foodImageId == null && other.foodImageId != null)
				|| (this.foodImageId != null && !this.foodImageId.equals(other.foodImageId))) {
			return false;
		}
		return true;
	}

	@Override
	public String toString() {
		return "FoodImage[" + foodImageId + " = " + foodImage + "]";
	}

}
