package com.eko.nerdeneyenir.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import com.owlike.genson.annotation.JsonIgnore;

// default package
// Generated 27.Tem.2014 21:21:56 by Hibernate Tools 3.4.0.CR1

/**
 * FoodCategory generated by hbm2java
 */
public class FoodCategory implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer foodCategoryId;
	private List<Food> foodList;
	private String name;

	public FoodCategory() {
	}

	public FoodCategory(String name) {
		this.name = name;
	}
	
	public Integer getFoodCategoryId() {
		return foodCategoryId;
	}

	public void setFoodCategoryId(Integer foodCategoryId) {
		this.foodCategoryId = foodCategoryId;
	}

	@JsonIgnore
	public List<Food> getFoodList() {
		if(foodList == null){
			foodList = new ArrayList<Food>();
		}
		return foodList;
	}

	public void setFoodList(List<Food> foodList) {
		this.foodList = foodList;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((foodCategoryId == null) ? 0 : foodCategoryId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object object) {
		if (!(object instanceof FoodCategory)) {
			return false;
		}
		FoodCategory other = (FoodCategory) object;
		if ((this.foodCategoryId == null && other.foodCategoryId != null)
				|| (this.foodCategoryId != null && !this.foodCategoryId.equals(other.foodCategoryId))) {
			return false;
		}
		return true;
	}

	@Override
	public String toString() {
		return "FoodCategory[" + foodCategoryId + " = " + name + "]";
	}

}
