package com.eko.nerdeneyenir.model;

// default package
// Generated 27.Tem.2014 21:21:56 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;

import com.owlike.genson.annotation.JsonIgnore;

/**
 * RestaurantAddress generated by hbm2java
 */
public class RestaurantAddress implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer restaddresId;
	private Restaurant restaurant;
	private String address;
	private String province;
	private String phone;
	private String website;
	private BigDecimal latitude;
	private BigDecimal longitude;

	public RestaurantAddress() {
		
	}

	public RestaurantAddress(Integer restaddresId, String address, String province, String phone, String website, 
			BigDecimal latitude, BigDecimal longitude) {
		super();
		this.restaddresId = restaddresId;
		this.address = address;
		this.province = province;
		this.phone = phone;
		this.website = website;
		this.latitude = latitude;
		this.longitude = longitude;
	}

	public Integer getRestaddresId() {
		return restaddresId;
	}

	public void setRestaddresId(Integer restaddresId) {
		this.restaddresId = restaddresId;
	}

	@JsonIgnore
	public Restaurant getRestaurant() {
		if(restaurant == null){
			restaurant = new Restaurant();
		}
		return restaurant;
	}

	public void setRestaurant(Restaurant restaurant) {
		this.restaurant = restaurant;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getProvince() {
		return province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getWebsite() {
		return website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	public BigDecimal getLatitude() {
		return latitude;
	}

	public void setLatitude(BigDecimal latitude) {
		this.latitude = latitude;
	}

	public BigDecimal getLongitude() {
		return longitude;
	}

	public void setLongitude(BigDecimal longitude) {
		this.longitude = longitude;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((restaddresId == null) ? 0 : restaddresId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object object) {
		if (!(object instanceof RestaurantAddress)) {
			return false;
		}
		RestaurantAddress other = (RestaurantAddress) object;
		if ((this.restaddresId == null && other.restaddresId != null)
				|| (this.restaddresId != null && !this.restaddresId.equals(other.restaddresId))) {
			return false;
		}
		return true;
	}

	@Override
	public String toString() {
		return "RestaurantAddress[id = " + restaddresId + "]";
	}

}
