package com.eko.nerdeneyenir.model;

// default package
// Generated 27.Tem.2014 21:21:56 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.owlike.genson.annotation.JsonIgnore;

/**
 * Restaurant generated by hbm2java
 */
public class Restaurant implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer restaurantId;
	private RestaurantAddress restaurantAddress;
	private List<Food> foods;
	private String name;
	private boolean restaurantActive;
	private Date insertDate;
	private Date updateDate;

	public Restaurant() {
		
	}

	public Restaurant(Integer restaurantId, RestaurantAddress restaurantAddress, String name,
			Date insertDate, Date updateDate) {
		super();
		this.restaurantId = restaurantId;
		this.restaurantAddress = restaurantAddress;
		this.name = name;
		this.insertDate = insertDate;
		this.updateDate = updateDate;
	}

	public Integer getRestaurantId() {
		return restaurantId;
	}

	public void setRestaurantId(Integer restaurantId) {
		this.restaurantId = restaurantId;
	}

	public RestaurantAddress getRestaurantAddress() {
		if(restaurantAddress == null){
			restaurantAddress = new RestaurantAddress();
		}
		return restaurantAddress;
	}

	public void setRestaurantAddress(RestaurantAddress restaurantAddress) {
		this.restaurantAddress = restaurantAddress;
	}

	@JsonIgnore
	public List<Food> getFoods() {
		if(foods == null){
			foods = new ArrayList<Food>();
		}
		return foods;
	}

	public void setFoods(List<Food> foods) {
		this.foods = foods;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getInsertDate() {
		return insertDate;
	}

	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	public Date getUpdateDate() {
		return updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public boolean isRestaurantActive() {
		return restaurantActive;
	}

	public void setRestaurantActive(boolean restaurantActive) {
		this.restaurantActive = restaurantActive;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((restaurantId == null) ? 0 : restaurantId.hashCode());
		return result;
	}

	@Override
    public boolean equals(Object obj) {
        if (this == obj)
               return true;   

        if (obj == null)
               return false;      

        if (getClass() != obj.getClass())
               return false;      

        Restaurant other = (Restaurant) obj;
        if (restaurantId == null) {
               if (other.restaurantId != null)
                      return false;
        } else if (!restaurantId.equals(other.restaurantId))
               return false;
        return true;
  }

	@Override
	public String toString() {
		return "Restaurant[" + restaurantId + " = " + name + "]";
	}

}
